version: '2'

services:
    web:
        container_name: forcast-app-web
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./build/nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        container_name: forcast-app-web-php
        build:
            context: ./build/php-fpm
        volumes:
            - ./code:/code
        networks:
            - code-network


    composer_installation:
        container_name: forcast-app-composer_installation
        image: composer
        volumes:
            - ./code:/code
        depends_on: 
            - php
        working_dir: /code
        command: composer install --ignore-platform-reqs

networks:
    code-network:
        driver: bridge
